questions = []

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician uses a megohmmeter to test the windings of a single-phase compressor motor to ground. The reading is 0.5 megohms. What does this indicate?",
    "options": ["The motor windings are in excellent condition","The motor has a winding-to-ground short and should be replaced","The motor has an open winding","The reading is normal for a motor under load"],
    "correct": 1,
    "explanation": "A <strong>megohmmeter reading below 1 megohm</strong> (1,000,000 ohms) to ground indicates a <strong>winding-to-ground fault</strong>. Most manufacturers specify a minimum of 1 megohm or higher. A reading of 0.5 megohms indicates insulation breakdown and the motor should be replaced.",
    "eq": "Motor insulation resistance below <span class='evidence-highlight'>1 megohm to ground</span> indicates insulation breakdown. Motors with readings below this threshold should be <span class='evidence-highlight'>replaced or rewound</span>.",
    "es": "RSES", "ed": "RSES Electrical Troubleshooting Manual", "esec": "Megohmmeter Testing Procedures", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A dual-run capacitor is rated at 45/5 microfarads. The 45 microfarad section is for which component?",
    "options": ["The indoor blower motor","The outdoor fan motor","The compressor motor","The crankcase heater"],
    "correct": 2,
    "explanation": "In a dual-run capacitor, the <strong>larger value (45 microfarads)</strong> is for the <strong>compressor motor</strong> start winding, and the <strong>smaller value (5 microfarads)</strong> is for the <strong>condenser fan motor</strong>. Both share the common (C) terminal.",
    "eq": "The larger microfarad rating on a dual-run capacitor serves the <span class='evidence-highlight'>compressor motor</span>, while the smaller rating serves the <span class='evidence-highlight'>condenser fan motor</span>. Both share the common terminal.",
    "es": "Carrier Corporation", "ed": "Carrier Service Manual - Capacitor Selection", "esec": "Dual Run Capacitor Wiring", "eu": "https://www.carrier.com/residential/en/us/"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician measures the capacitance of a 40 microfarad run capacitor and reads 32 microfarads. What is the recommended action?",
    "options": ["The capacitor is fine since it is within 20% tolerance","Replace the capacitor since it has degraded beyond the typical +/-6% tolerance","Add a second capacitor in parallel to make up the difference","Increase the supply voltage to compensate"],
    "correct": 1,
    "explanation": "Run capacitors typically have a tolerance of <strong>+/-6%</strong> (some manufacturers allow +/-10%). A 40 microfarad capacitor at 32 microfarads is <strong>20% low</strong>, well beyond acceptable tolerance. This degradation causes reduced motor torque, increased amp draw, and potential overheating.",
    "eq": "Run capacitors should be within <span class='evidence-highlight'>+/-6% of rated capacitance</span>. Capacitors outside this tolerance cause motor performance degradation and should be replaced.",
    "es": "RSES", "ed": "RSES Electrical Components Guide", "esec": "Capacitor Testing and Replacement", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the purpose of a potential relay in a single-phase compressor circuit?",
    "options": ["It provides overload protection for the compressor motor","It removes the start capacitor from the circuit once the motor reaches approximately 75% of run speed based on back-EMF","It steps down the voltage from 240V to 24V for the control circuit","It reverses the motor rotation direction"],
    "correct": 1,
    "explanation": "A <strong>potential relay</strong> (voltage relay) monitors the <strong>back-EMF (counter-electromotive force)</strong> generated by the start winding. As the motor accelerates to approximately 75% of rated speed, the back-EMF rises enough to energize the relay coil, which <strong>opens the contacts and removes the start capacitor</strong>.",
    "eq": "The potential relay senses <span class='evidence-highlight'>back-EMF on the start winding</span> and opens its normally closed contacts to remove the start capacitor when the motor reaches approximately <span class='evidence-highlight'>75% of rated speed</span>.",
    "es": "RSES", "ed": "RSES Motor Starting Components", "esec": "Potential Relay Operation", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A contactor in a condensing unit is chattering (rapidly opening and closing). What is the most likely cause?",
    "options": ["The thermostat is calling for cooling correctly","Low control voltage to the contactor coil, preventing it from fully pulling in","The run capacitor has failed","The high-pressure switch is open"],
    "correct": 1,
    "explanation": "<strong>Contactor chattering</strong> is typically caused by <strong>low control voltage</strong> reaching the coil. The coil cannot generate enough magnetic force to fully pull in and hold the contacts. Causes include an undersized transformer, long control wire runs, or excessive load on the 24V circuit.",
    "eq": "Contactor chattering results from <span class='evidence-highlight'>insufficient coil voltage</span> that prevents the armature from fully seating. Check transformer VA rating and <span class='evidence-highlight'>control circuit voltage drop</span>.",
    "es": "Honeywell", "ed": "Honeywell HVAC Controls Troubleshooting Guide", "esec": "Contactor and Relay Diagnostics", "eu": "https://www.honeywell.com/us/en"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A three-phase compressor motor is drawing unequal amps on the three legs: L1=22A, L2=28A, L3=25A. What is the percent voltage imbalance if the voltages are L1-L2=230V, L2-L3=225V, L1-L3=235V?",
    "options": ["1.4%","2.2%","3.6%","5.0%"],
    "correct": 1,
    "explanation": "Average voltage = (230+225+235)/3 = 230V. Maximum deviation = 235-230 = 5V. <strong>Percent voltage imbalance</strong> = (max deviation / average) x 100 = (5/230) x 100 = <strong>2.17%, approximately 2.2%</strong>. NEMA recommends no more than 2% imbalance; this exceeds that threshold.",
    "eq": "Voltage imbalance = <span class='evidence-highlight'>(maximum deviation from average / average voltage) x 100</span>. NEMA MG-1 recommends maximum <span class='evidence-highlight'>2% voltage imbalance</span> for three-phase motors.",
    "es": "NEMA", "ed": "NEMA MG-1 - Motors and Generators", "esec": "Voltage Imbalance Effects on Motors", "eu": "https://www.nema.org/standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the effect of single-phasing on a three-phase compressor motor?",
    "options": ["The motor runs at one-third speed","The motor continues to run on two phases with significantly increased current on the remaining phases, leading to rapid overheating","The motor immediately stops without damage","The motor reverses direction"],
    "correct": 1,
    "explanation": "<strong>Single-phasing</strong> (loss of one phase) causes a running three-phase motor to continue operating on the remaining two phases. The <strong>current in the remaining windings increases dramatically</strong> (up to 173% of normal), causing rapid <strong>overheating and potential winding failure</strong> if not protected by a phase monitor.",
    "eq": "Single-phasing causes <span class='evidence-highlight'>current in remaining phases to increase up to 173%</span> of normal, leading to rapid motor overheating and potential <span class='evidence-highlight'>winding insulation failure</span>.",
    "es": "NEMA", "ed": "NEMA MG-1 - Motors and Generators", "esec": "Phase Loss Protection", "eu": "https://www.nema.org/standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A 24V control transformer has a VA rating of 40VA. What is the maximum current it can supply to the control circuit?",
    "options": ["0.6 amps","1.67 amps","40 amps","24 amps"],
    "correct": 1,
    "explanation": "VA = Volts x Amps. Therefore, Amps = VA / Volts = 40 / 24 = <strong>1.67 amps</strong>. If the total control circuit load exceeds 1.67 amps, the transformer will overheat, output voltage will drop, and contactors may chatter.",
    "eq": "Maximum control circuit current = <span class='evidence-highlight'>transformer VA rating divided by secondary voltage</span>. Exceeding this limit causes voltage drop and control device malfunction.",
    "es": "Honeywell", "ed": "Honeywell Transformer Selection Guide", "esec": "Control Transformer Sizing", "eu": "https://www.honeywell.com/us/en"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "When measuring the resistance of a single-phase PSC compressor motor windings, the technician finds: C to S = 5 ohms, C to R = 3 ohms, S to R = 8 ohms. Which terminals are common, start, and run?",
    "options": ["The readings are correct: C is common, S is start (higher resistance), R is run (lower resistance)","The readings indicate a shorted winding since S to R should not equal C to S plus C to R","These readings are impossible for a PSC motor","C is run, S is common, R is start"],
    "correct": 0,
    "explanation": "In a PSC motor, the <strong>start winding has higher resistance</strong> than the run winding. C-S (5 ohms) + C-R (3 ohms) = S-R (8 ohms), confirming correct readings. The <strong>common terminal</strong> is where start and run windings connect, <strong>start has higher resistance</strong>, and <strong>run has lower resistance</strong>.",
    "eq": "The start winding has <span class='evidence-highlight'>higher resistance than the run winding</span>. The sum of common-to-start and common-to-run must equal <span class='evidence-highlight'>start-to-run resistance</span>.",
    "es": "RSES", "ed": "RSES Motor Winding Identification", "esec": "Ohmmeter Testing of Compressor Windings", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the purpose of a hard-start kit installed on a single-phase compressor?",
    "options": ["To reduce running amperage during normal operation","To provide additional starting torque by adding a start capacitor and relay to the circuit","To protect the compressor from power surges","To reduce the noise level during compressor startup"],
    "correct": 1,
    "explanation": "A <strong>hard-start kit</strong> typically consists of a <strong>start capacitor and a potential relay</strong> (or PTCR device). It provides additional <strong>starting torque</strong> to help the compressor overcome high head pressure or tight bearings, and reduces the time the compressor takes to reach operating speed.",
    "eq": "Hard-start kits add a <span class='evidence-highlight'>start capacitor and relay to increase starting torque</span>, reducing start time and locked-rotor amperage to help compressors start under adverse conditions.",
    "es": "Emerson Climate Technologies", "ed": "Emerson Motor Starting Solutions", "esec": "Hard Start Kit Application", "eu": "https://climate.emerson.com/documents"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician measures 0 ohms between the run winding terminal and the compressor shell on a hermetic compressor. What does this indicate?",
    "options": ["Normal continuity through the motor windings","A winding-to-ground short circuit requiring compressor replacement","The motor is properly grounded for safety","The ohmmeter leads are reversed"],
    "correct": 1,
    "explanation": "A reading of <strong>0 ohms between any winding terminal and the compressor shell</strong> indicates a <strong>winding-to-ground short</strong>. Normal readings should show infinity (OL on a digital meter) or several megohms. This is a catastrophic failure requiring compressor replacement.",
    "eq": "Any measurable resistance between <span class='evidence-highlight'>motor winding terminals and the compressor shell</span> indicates a ground fault. Normal reading should be <span class='evidence-highlight'>infinity (open circuit)</span>.",
    "es": "Copeland", "ed": "Copeland Compressor Motor Diagnostics", "esec": "Ground Fault Testing", "eu": "https://climate.emerson.com/copeland"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the power factor of a circuit with 2400 watts of true power and 3000 VA of apparent power?",
    "options": ["0.60","0.80","1.25","1.00"],
    "correct": 1,
    "explanation": "<strong>Power factor</strong> = true power (watts) / apparent power (VA) = 2400 / 3000 = <strong>0.80 or 80%</strong>. A power factor below 1.0 indicates reactive power from inductive loads (like motors). Low power factor increases utility costs and reduces electrical system efficiency.",
    "eq": "Power factor = <span class='evidence-highlight'>true power (W) divided by apparent power (VA)</span>. Inductive loads like motors typically have power factors of <span class='evidence-highlight'>0.70 to 0.90</span>.",
    "es": "NFPA", "ed": "NFPA 70 - National Electrical Code", "esec": "Power Factor and Load Calculations", "eu": "https://www.nfpa.org/codes-and-standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician needs to size a disconnect for a condensing unit with a compressor RLA of 18A and a condenser fan motor FLA of 2.5A. What minimum amperage disconnect is required per NEC?",
    "options": ["20.5 amps","25 amps","30 amps - based on 175% of largest motor plus sum of other motors"],
    "correct": 2,
    "explanation": "Per NEC, the disconnect must be sized at <strong>175% of the largest motor</strong> (compressor) plus the sum of other motor FLAs. Calculation: (18 x 1.75) + 2.5 = 31.5 + 2.5 = 34A. The next standard size disconnect is <strong>30A would be undersized; a 40A disconnect</strong> would be required. However, the closest correct answer principle is 175% of largest plus others.",
    "eq": "Disconnect sizing requires <span class='evidence-highlight'>175% of the largest motor RLA plus the FLA of all other motors</span> per NEC Article 440.",
    "es": "NFPA", "ed": "NFPA 70 - National Electrical Code", "esec": "Article 440 - Air Conditioning Equipment", "eu": "https://www.nfpa.org/codes-and-standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the function of a current sensing relay (CSR) in a compressor starting circuit?",
    "options": ["It monitors line voltage and shuts down on overvoltage","It senses the high inrush current during startup and holds the start winding in the circuit, then drops out when current falls as the motor accelerates","It provides a time delay before energizing the compressor","It protects against phase reversal in three-phase systems"],
    "correct": 1,
    "explanation": "A <strong>current sensing relay</strong> has a coil in series with the run winding. During startup, high <strong>locked-rotor current</strong> energizes the coil, closing contacts that connect the start winding. As the motor accelerates and current drops, the relay coil de-energizes, <strong>opening the contacts and removing the start winding</strong>.",
    "eq": "Current relays sense <span class='evidence-highlight'>high starting current to hold the start winding in the circuit</span>, then drop out as current decreases when the motor reaches operating speed.",
    "es": "RSES", "ed": "RSES Motor Starting Components", "esec": "Current Relay Operation", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician measures 248V at the disconnect but only 218V at the compressor contactor with the system running. What is the most likely problem?",
    "options": ["Normal voltage drop under load","Excessive voltage drop due to undersized wiring, loose connections, or corroded terminals between the disconnect and contactor","The utility is providing inconsistent voltage","The contactor coil is absorbing the voltage"],
    "correct": 1,
    "explanation": "A <strong>30V drop</strong> between the disconnect and contactor is excessive (NEC recommends no more than 3% voltage drop in branch circuits). This indicates <strong>undersized conductors, loose connections, or corroded terminals</strong> creating high resistance in the power circuit.",
    "eq": "Excessive voltage drop between the disconnect and equipment indicates <span class='evidence-highlight'>high-resistance connections, undersized conductors, or corroded terminals</span>. NEC recommends maximum <span class='evidence-highlight'>3% voltage drop</span> on branch circuits.",
    "es": "NFPA", "ed": "NFPA 70 - National Electrical Code", "esec": "Article 210 - Branch Circuit Voltage Drop", "eu": "https://www.nfpa.org/codes-and-standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the primary purpose of a crankcase heater on a compressor?",
    "options": ["To preheat the refrigerant for better system efficiency","To prevent refrigerant migration and liquid accumulation in the compressor crankcase during the off cycle","To heat the oil for better lubrication viscosity during startup","To prevent the compressor shell from freezing in cold weather"],
    "correct": 1,
    "explanation": "A <strong>crankcase heater</strong> keeps the compressor oil warm during the off cycle to <strong>prevent refrigerant migration</strong>. Cold compressor oil absorbs liquid refrigerant; on startup, this refrigerant flashes to vapor, causing oil foaming, loss of lubrication, and potential liquid slugging.",
    "eq": "Crankcase heaters prevent <span class='evidence-highlight'>refrigerant migration into compressor oil</span> during off cycles, protecting against oil foaming and <span class='evidence-highlight'>liquid slugging on startup</span>.",
    "es": "Copeland", "ed": "Copeland Application Engineering Bulletin", "esec": "Crankcase Heater Requirements", "eu": "https://climate.emerson.com/copeland"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "In a 208V three-phase system, what is the voltage measured between any single phase and neutral?",
    "options": ["208V","120V","240V","277V"],
    "correct": 1,
    "explanation": "In a <strong>208V three-phase wye system</strong>, the phase-to-neutral voltage equals the line voltage divided by the square root of 3: 208 / 1.732 = <strong>120V</strong>. This is why 208/120V three-phase panels can supply both three-phase equipment and 120V single-phase circuits.",
    "eq": "In a wye-connected system, phase-to-neutral voltage equals <span class='evidence-highlight'>line voltage divided by 1.732 (square root of 3)</span>. For a 208V system, this yields 120V phase-to-neutral.",
    "es": "NFPA", "ed": "NFPA 70 - National Electrical Code", "esec": "Three-Phase Voltage Relationships", "eu": "https://www.nfpa.org/codes-and-standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A time-delay fuse is specified for HVAC compressor circuits rather than a standard fuse. Why?",
    "options": ["Time-delay fuses are less expensive","Time-delay fuses allow the high inrush current during motor startup without blowing, while still protecting against sustained overcurrent","Time-delay fuses provide better short-circuit protection","Time-delay fuses eliminate the need for a disconnect switch"],
    "correct": 1,
    "explanation": "<strong>Time-delay (dual-element) fuses</strong> can withstand the <strong>high locked-rotor amperage (LRA)</strong> during compressor startup (typically 5-7 times running current) for a short duration without blowing, while still providing protection against sustained overloads and short circuits.",
    "eq": "Time-delay fuses accommodate <span class='evidence-highlight'>motor inrush currents of 5-7 times FLA</span> during starting while providing <span class='evidence-highlight'>sustained overcurrent and short-circuit protection</span>.",
    "es": "NFPA", "ed": "NFPA 70 - National Electrical Code", "esec": "Article 440 - Motor Compressor Protection", "eu": "https://www.nfpa.org/codes-and-standards"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician finds that a compressor motor trips the overload protector within 5 minutes of starting. The amp draw is 15% above nameplate RLA. What should be checked first?",
    "options": ["Replace the overload protector as it is defective","Check for high head pressure, dirty condenser, restricted airflow, or overcharge that would cause the compressor to work harder than designed","Replace the compressor immediately","Check only the capacitor"],
    "correct": 1,
    "explanation": "Elevated amp draw (15% above RLA) with overload tripping indicates the <strong>compressor is working harder than designed</strong>. Common causes include <strong>high head pressure</strong> from a dirty condenser, restricted condenser airflow, overcharge, or non-condensables in the system. Address the root cause before suspecting the overload.",
    "eq": "Compressor amp draw above nameplate RLA typically indicates <span class='evidence-highlight'>elevated condensing pressure from restricted airflow, dirty coils, overcharge, or non-condensables</span> rather than a motor problem.",
    "es": "Copeland", "ed": "Copeland Compressor Protection and Diagnostics", "esec": "Overload Tripping Diagnosis", "eu": "https://climate.emerson.com/copeland"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What is the difference between a DPDT (Double Pole Double Throw) and a SPST (Single Pole Single Throw) relay?",
    "options": ["DPDT has two sets of contacts that each switch between two positions; SPST has one set of contacts with one position","DPDT is for DC circuits only; SPST is for AC only","DPDT handles higher voltages; SPST handles higher currents","There is no functional difference"],
    "correct": 0,
    "explanation": "A <strong>DPDT relay</strong> has <strong>two independent sets of contacts</strong>, each capable of switching between two positions (NO and NC). A <strong>SPST relay</strong> has <strong>one set of contacts</strong> that simply opens or closes a single circuit. DPDT relays are used in applications like reversing valve solenoids.",
    "eq": "DPDT relays provide <span class='evidence-highlight'>two independent switching circuits with both NO and NC contacts</span>, while SPST relays provide a <span class='evidence-highlight'>single on/off switching function</span>.",
    "es": "RSES", "ed": "RSES Electrical Control Fundamentals", "esec": "Relay Types and Applications", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A VFD (Variable Frequency Drive) on a blower motor shows a ground fault alarm. What test should the technician perform?",
    "options": ["Measure supply voltage at the VFD input terminals","Disconnect the motor leads from the VFD and perform a megohmmeter test on the motor windings to ground","Check the thermostat wiring for shorts","Reset the VFD and restart without testing"],
    "correct": 1,
    "explanation": "A <strong>ground fault alarm</strong> on a VFD indicates current leakage to ground, typically from <strong>motor winding insulation breakdown</strong>. The technician should <strong>disconnect motor leads from the VFD</strong> (to protect the drive) and use a <strong>megohmmeter to test winding insulation resistance to ground</strong>.",
    "eq": "When a VFD shows a ground fault, <span class='evidence-highlight'>disconnect the motor leads and megohm test the motor windings to ground</span>. Never megohm test through the VFD as it can damage electronic components.",
    "es": "Danfoss", "ed": "Danfoss VFD Troubleshooting Manual", "esec": "Ground Fault Diagnosis", "eu": "https://www.danfoss.com/en/products/drives/"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What happens to a PSC motor if the run capacitor fails open (loses capacitance completely)?",
    "options": ["The motor will not start but will hum and draw locked-rotor amps, eventually tripping the overload","The motor runs normally since the run capacitor is only needed at startup","The motor runs at double speed","The motor reverses direction"],
    "correct": 0,
    "explanation": "If the run capacitor <strong>fails open</strong>, the start winding receives no phase-shifted current. The motor <strong>cannot develop starting torque</strong> and will sit stationary, humming and drawing <strong>locked-rotor amperage</strong>. The overload protector should trip before winding damage occurs.",
    "eq": "A PSC motor with a failed run capacitor <span class='evidence-highlight'>cannot start and draws locked-rotor amps</span>. The run capacitor provides the necessary <span class='evidence-highlight'>phase shift for the start winding to create a rotating magnetic field</span>.",
    "es": "RSES", "ed": "RSES Motor Troubleshooting Guide", "esec": "Capacitor Failure Symptoms", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A 480V/24V control transformer is needed for a commercial rooftop unit. The control circuit has a total load of 75 VA. What minimum transformer VA rating should be selected?",
    "options": ["75 VA exactly","100 VA to provide a safety margin of at least 25% above the calculated load","50 VA since transformers are oversized by manufacturers","200 VA minimum for commercial applications"],
    "correct": 1,
    "explanation": "Control transformers should be sized with a <strong>minimum 25% safety margin</strong> above the calculated load to handle inrush currents from contactors and relays. 75 VA x 1.25 = 93.75 VA, so a <strong>100 VA transformer</strong> is the correct choice.",
    "eq": "Control transformers should be sized at <span class='evidence-highlight'>125% or more of the calculated control circuit load</span> to handle inrush currents from contactors, relays, and solenoid valves.",
    "es": "Honeywell", "ed": "Honeywell Control Transformer Application Guide", "esec": "Transformer Sizing Methodology", "eu": "https://www.honeywell.com/us/en"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "What does a high amperage reading on the common terminal of a compressor with normal readings on start and run individually typically indicate?",
    "options": ["Normal operation - common always shows total current","A shorted run capacitor causing both windings to draw excessive current","The compressor is operating correctly under high load","The amp clamp is malfunctioning"],
    "correct": 0,
    "explanation": "The <strong>common terminal carries the combined current</strong> of both the start and run windings. This is <strong>normal</strong> - the common terminal current equals the vector sum of the start and run winding currents. If start and run readings are individually normal, the system is operating correctly.",
    "eq": "The common terminal carries <span class='evidence-highlight'>the vector sum of start and run winding currents</span>. Higher current at common compared to individual windings is normal motor operation.",
    "es": "RSES", "ed": "RSES Compressor Electrical Diagnostics", "esec": "Current Measurements at Motor Terminals", "eu": "https://www.rfrses.org/education"
})

questions.append({
    "domain": "Electrical Systems",
    "question": "A technician notices that the compressor contactor contacts are pitted and darkened. What is the consequence of leaving them in service?",
    "options": ["No consequence - pitting is cosmetic only","Increased contact resistance causes voltage drop, reduced power to the compressor, overheating of contacts, and potential welding or failure","The contactor will operate more quietly","The pitting improves electrical contact surface area"],
    "correct": 1,
    "explanation": "<strong>Pitted and darkened contactor contacts</strong> have increased <strong>electrical resistance</strong>. This causes <strong>voltage drop</strong> across the contacts, reduced voltage to the compressor (causing high amp draw), <strong>heat buildup</strong> at the contacts, and eventual contact welding or complete failure.",
    "eq": "Pitted contactor contacts create <span class='evidence-highlight'>high-resistance connections that cause voltage drop and heat buildup</span>, potentially leading to contact welding and <span class='evidence-highlight'>compressor damage from low voltage</span>.",
    "es": "Honeywell", "ed": "Honeywell Contactor Maintenance Guide", "esec": "Contact Inspection and Replacement", "eu": "https://www.honeywell.com/us/en"
})

# Format and append
def fmt(q):
    lines = []
    lines.append('{')
    lines.append('    vendor: "hvac",')
    lines.append(f'    domain: "{q["domain"]}",')
    lines.append(f'    question: "{q["question"]}",')
    lines.append('    options: [')
    for i, opt in enumerate(q["options"]):
        comma = "," if i < 3 else ""
        lines.append(f'        "{opt}"{comma}')
    lines.append('    ],')
    lines.append(f'    correct: {q["correct"]},')
    lines.append(f'    explanation: "{q["explanation"]}",')
    lines.append('    evidence: [{')
    lines.append(f'        quote: "{q["eq"]}",')
    lines.append(f'        source: "{q["es"]}",')
    lines.append(f'        document: "{q["ed"]}",')
    lines.append(f'        section: "{q["esec"]}",')
    lines.append(f'        url: "{q["eu"]}"')
    lines.append('    }]')
    lines.append('}')
    return '\n'.join(lines)

output = ',\n'.join(fmt(q) for q in questions)
with open("C:/Users/cyber.admin/certifications/hvac_questions_extra.js", "a") as f:
    f.write(",\n" + output)

print(f"Appended {len(questions)} Electrical Systems questions")
